# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- development

pool:
  vmImage: ubuntu-latest

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '10.x'
      checkLatest: true
    displayName: "Install Node.js"

  - script: |
      npm install
      npm run test:ci
    displayName: "npm install and test"
    env:
      SECRETKEY_REFRESH: $(secret_key_refresh)
      SECRETKEY_ACCESS: $(secret_key_access)
  
  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testRunner: JUnit
      testResultsFiles: "**/test-results.xml"

  - task: Docker@2
    inputs:
      containerRegistry: 'gabgc Docker Hub'
      repository: 'sirius-auth'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile.auth'
  
  - task: Docker@2
    inputs:
      containerRegistry: 'gabgc Docker Hub'
      repository: 'sirius-buddy'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile.buddy'

  - task: Docker@2
    inputs:
      containerRegistry: 'gabgc Docker Hub'
      repository: 'sirius-user'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile.user'

  - task: Docker@2
    inputs:
      containerRegistry: 'gabgc Docker Hub'
      repository: 'sirius-realtime'
      command: 'buildAndPush'
      Dockerfile: '$(Build.SourcesDirectory)/docker/Dockerfile.realtime'
  
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'set'
      arguments: 'image deployment/sirius-user sirius-user=sirius-user:$(Build.BuildId)'
  
  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'set'
      arguments: 'image deployment/sirius-auth sirius-auth=sirius-auth:$(Build.BuildId)'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'set'
      arguments: 'image deployment/sirius-buddy sirius-buddy=sirius-buddy:$(Build.BuildId)'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'set'
      arguments: 'image deployment/sirius-realtime sirius-realtime=sirius-realtime:$(Build.BuildId)'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'rollout'
      arguments: 'restart deployment/sirius-auth'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'rollout'
      arguments: 'restart deployment/sirius-user'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'rollout'
      arguments: 'restart deployment/sirius-buddy'

  - task: Kubernetes@1
    inputs:
      connectionType: 'Kubernetes Service Connection'
      kubernetesServiceEndpoint: 'okteto k8s'
      namespace: 'gabgc'
      command: 'rollout'
      arguments: 'restart deployment/sirius-realtime'