version: "3.2"

services:
  auth:
    container_name: auth_service
    build:
      dockerfile: ./docker/Dockerfile.auth
      context: .
    environment:
      - "HOST=auth"
      - "DBURL=db"
    ports:
      - "3001:80"

  buddy:
    container_name: buddy_service
    build:
      dockerfile: ./docker/Dockerfile.buddy
      context: .
    environment:
      - "HOST=buddy"
      - "DBURL=db"
    ports:
      - "3002:80"

  user:
    container_name: user_service
    build:
      dockerfile: ./docker/Dockerfile.user
      context: .
    environment:
      - "HOST=user"
      - "DBURL=db"
    ports:
      - "3003:80"

  realtime:
    container_name: realtime_service
    build:
      dockerfile: ./docker/Dockerfile.realtime
      context: .
    environment:
      - "HOST=real_time"
      - "DBURL=db"
    ports:
      - "3004:80"

  db:
    container_name: db
    build:
      dockerfile: ./docker/Dockerfile.db
      context: .
    ports:
      - "5432:5432"
