FROM node:latest
ENV NODE_ENV=testing
ENV PORT=80

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]
RUN npm install
COPY . .
RUN npm run build
EXPOSE 80
CMD ["node", "./dist/buddy/main.js"]