FROM node:latest
ENV NODE_ENV=testing
ENV PORT=80

WORKDIR /app

COPY ["package.json", "yarn.lock", "./"]
RUN yarn install
COPY . .
RUN npm run build
EXPOSE 80
CMD ["node", "./dist/real_time/main.js"]